name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: yarn install
      run: yarn
    - name: do package
      run: |
        yarn dist
